import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { getSession } from "@/components/utils/CacheSession";
import LoginPage from "@/features/auth/LoginPage";
import ReactQueryProvider from "@/lib/ReactQueryProvider";
import { SidebarLeft } from "@/features/sidebarLeft/SidebarLeft";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession()
  if(!session){
    return <>
      <html lang="en">
        <body>
          <LoginPage />
        </body>
      </html>
    </>
  }

  return (
    <html lang="en">
      <body className={"max-w-[1700px] mx-auto relative " + inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>
            <div className="flex">
                <div className="fixed z-10 inset-0 pointer-events-none">
                  <div className="absolute -top-5 -left-5 w-32 h-32 bg-red-500/20 rounded-full blur-md animate-pulse"></div>
                  <div className="absolute -top-5 -right-5 w-32 h-32 bg-blue-500/20 rounded-full blur-md animate-pulse"></div>
                  <div className="absolute -bottom-5 -left-5 w-32 h-32 bg-green-500/20 rounded-full blur-md animate-pulse"></div>
                  <div className="absolute -bottom-5 -right-5 w-32 h-32 bg-yellow-500/20 rounded-full blur-md animate-pulse"></div>
                </div>
              <ReactQueryProvider>
                <SidebarLeft />
                {children}
              </ReactQueryProvider>
              </div>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
