import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { SidebarMenu } from "@/features/sidebarMenu/SidebarMenu";
import { getSession } from "@/components/utils/CacheSession";
import { LoginPage } from "@/features/auth/LoginPage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession()
  if(!session){
    return <>
      <html lang="en">
        <body>
          <LoginPage />
        </body>
      </html>
    </>
  }

  return (
    <html lang="en">
      <body className={"bg-[#000000] text-white " + inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>
            <div className="flex max-w-[1200px] mx-auto">
              <SidebarMenu />
              <div className="flex-1">
                {children}
              </div>
            </div>
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
